### ISSUE TITLE
service worker 缓存导致本地版本跟不上服务端版本

### ISSUE THREAD

**Issue by lxfriday** [mdnice/markdown-nice-editor#1]
## 原因

参考 [浅谈PWA](https://juejin.im/post/5bed580cf265da6166240a1e#heading-3) 4.1.4 Service Worker版本更新

service worker 更新策略导致，需要关闭浏览器然后打开才会应用最新的版本。

**Comment by guanpengchn** [comment]
[谨慎处理 Service Worker 的更新](https://juejin.im/post/5c81cc985188257df17f109c)
